### ISSUE TITLE
[Korekto][TP1] première séance à compléter avant le 10/02/2020 23h00

### ISSUE THREAD

**Issue by ledoyen** [Hyrla/super-projet-4A#7]
Votre exercice n'est pas complet :
* Statut du build dans Travis doit être **passed**, see https://travis-ci.com/hyrla/super-projet-4a.
* Badge Travis manquant dans le fichier [README.md](https://github.com/hyrla/super-projet-4a/blob/master/README.md) : [![Build Status](https://travis-ci.com/hyrla/super-projet-4a.svg?branch=master)](https://travis-ci.com/hyrla/super-projet-4a)
* Badge Codecov manquant dans le fichier [README.md](https://github.com/hyrla/super-projet-4a/blob/master/README.md) : [![codecov](https://codecov.io/gh/hyrla/super-projet-4a/branch/master/graph/badge.svg)](https://codecov.io/gh/hyrla/super-projet-4a)

Rappel du sujet : https://github.com/ledoyen/tp-java/blob/master/projet/4A_2020/TP.md.  
Vous avez jusqu'au 10/02/2020 23h pour ajouter et/ou corriger ces erreurs.  
Au delà de cette date, la première séance de TP sera considérée incomplète et la note du projet sera réduite de 2 points.

**Comment by Hyrla** [comment]
Bonjour Monsieur,

Je suis désolé, je viens seulement de prendre connaissance de votre
commentaire. En effet, nous revenons tout juste du Colloque ESIEA et nous
avions une couverture réseau extrêmement limitée (pour ne pas dire
inexistante). Nous allons ajouter les éléments manquants au plus vite.

Nous vous remercions par avance de votre compréhension.

Bien cordialement,

Gauthier Heiss

Le mar. 4 févr. 2020 à 01:11, Loïc Ledoyen <notifications@github.com> a
écrit :
